### PR TITLE
Update React-Native and dependent packages

### PR DESCRIPTION
**Pull request by lukevp**
Update react-native and dependent packages to support the latest version of React Native.  This PR is in advance of an update to the example app to better support hot reloading, hooks, and typescript.

### CODE REVIEW

**Comment by darryncampbell** [comment]
Thank you.  Please let me know when this pull request is ready for review

**Comment by lukevp** [comment]
This PR can be individually reviewed and merged, it works as-is. That will reduce the # of changes that show up in the next PR since it will depend on this one. I wanted to keep the React Native upgrade separate from the rewrite to Hooks.

**Comment by darryncampbell** [comment]
Thanks for the clarity, I have merged this.

**Comment by lukevp** [comment]
Thanks @darryncampbell!

**Pull request merged**
